name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: hadolint/hadolint

    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.4.0
        with:
          dockerfile: Dockerfile
      - uses: hadolint/hadolint-action@v1.4.0
        with:
          dockerfile: ci/Dockerfile
      - uses: hadolint/hadolint-action@v1.4.0
        with:
          dockerfile: docker-compose/Dockerfile
      - uses: hadolint/hadolint-action@v1.4.0
        with:
          dockerfile: fpm/Dockerfile
      - uses: hadolint/hadolint-action@v1.4.0
        with:
          dockerfile: php-7.4/Dockerfile
